### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by xLink** [Toddish/Verify-L4#34]
So far this has proven to be awesome, handles nearly every use case i have, now whilst i could also handle this one myself, I think it would benefit the package to have a standard set of Events to hook things into.

Eg, 
verify.auth.login
verify.auth.logout
verify.role.subscribed 
verify.role.unsubscribed

just a few of the top of my head. These should allow us to act on events that are thrown etc

**Comment by Toddish** [comment]
Having looked into this again, I think it's better to let people add their own events in their projects.

I don' think event code should be forced into Verify, it'd be a bit of a hack, when it really should be aprt of the project's logic.
