### ISSUE TITLE
Remove UserNotFoundException

### ISSUE THREAD

**Issue by smartfaceweb** [Toddish/Verify-L4#43]
It might be a better solution to remove the following code from line 96 of the VerifyUserProvider class:

```
throw new UserNotFoundException('User can not be found');
```

As the retrieveByCredentials function is used by other things like the PasswordBroker class in the reminder package, your code actually disables some of those features such as being able to return a value from Password::remind.

**Comment by Toddish** [comment]
I'll probably rework how the errors work when I create a L5 version of the package, so marking this as closed for now.
