### ISSUE TITLE
Performance Verify with a lot of permissions

### ISSUE THREAD

**Issue by Thijmen** [Toddish/Verify-L4#57]
Hi,

Let me explain what I am trying to do;
I created a website in which I manage my projects. A project has many hours, tickets, credentials, notes etc. 
What I want, is that I can decide which user is allowed to create a ticket in a project. 

I tried to extend the auth library, but had no succes. Now, I want to create permissions like:
`create_ticket_project_6`, `view_ticket_project_6`, `delete_credential_project_6`. 

I think I have around 15 basic permissions per project.
In a month, my website has around 15~20 projects. 20 * 15 = 300 permissions.

My question is; how does Verify copes with this may permissions? Maybe you have another suggestion for my casus; feel free to reply.

Thanks

**Comment by Toddish** [comment]
Going to close this, as I think it's out of the scope of what Verify is/can do.
