### ISSUE TITLE
Super Admin can vs is

### ISSUE THREAD

**Issue by andregeges** [Toddish/Verify-L4#74]
hi, when i added filter to pass if user CAN something. it is no problem with super admin i can pass all rule
but when i added filter to pass if user IS sales or somethnig, when i used Super Admin login i cannot pass the rule..

i want with super admin login i can go to all my features, but when i added filter by is('Sales') i cannot pass it..

**Comment by Toddish** [comment]
Hey,

I'm not 100% sure what you mean. Can you post some of your code?

**Comment by andregeges** [comment]
My login now is super_admin, and i not put any permission in this role..

```
\Auth::user()->can('edit_post')
```
return true


```
\Auth::user()->is('moderator')
```
return false

**Comment by Toddish** [comment]
That's because Super Admin is actually a role.

With ->is(), you're checking against the role, so it'll return false.

You could just override the is method in your User class to return true if the user is a Super Admin.
