### ISSUE TITLE
Update to Laravel 5

### ISSUE THREAD

**Issue by Grey2k** [Toddish/Verify-L4#76]
subj

**Comment by christian-thomas** [comment]
I've forked the package for a current L5 project if you want to use that. Composer snippet below:

	"require": {
		"toddish/verify": "dev-laravel5",
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/industrious-mouse/Verify-L4"
		}
	],

**Comment by Toddish** [comment]
Cheers Christian :D

This is on my list of things to do, I was mainly just trying to decide if it should be a new version number, or an entirely new package.

Screwed myself over a little with Toddish/Verify, Toddish/Verify-L4 etc.

**Comment by Maxime-BHA** [comment]
@Toddish 

Why not renaming out this repository Toddish/Verify instead of giving the Verify-L3 this name, and all the version in his own branch/release-tag and so keeping out the name Verify as this package is well known for it simplicity and extensibility, except if you're making majors changes, there is no reason for a name change, multiples repositories are mind-blowing and should be chosen only if there is majors changes.. like Guzzle packages (Guzzle 3 and his components to Guzzle 5)

Also we can consider that Verify 1.0 to 3.1.0 and all version 3.x are for Laravel 4, and new release (per exemple Verify 4.X) are for Laravel 5, just like the current version logic from Laravel.

Maybe @christian-thomas should be pushing his PR to develop/master or a specific branch including some documentation changes (because packages aren't working the same way as Laravel 4)

**Comment by Toddish** [comment]
Ideally, that's the best solution (it's been brought up in #41 too).

The only thing that was stopping me, was I'd lose all stats on packagist. Which isn't a massive deal, just a bit annoying.

**Comment by Grey2k** [comment]
christian-thomas .  using your fork - work nice, only thing - need to manually add verify.php config in config dir, publishing not working.

**Comment by Grey2k** [comment]
@Toddish - think while L4 still supports think its need to be a new package L5  =)

**Comment by Maxime-BHA** [comment]
@Grey2k and @Toddish  actually we can continue to host Verify on this repository, in all case, renaming or creating a new package means losing stats, we can continue to support Verify on Laravel 4 as Laravel 4 is still supported and continued by Laravel Teams and Taylor Otweel.

Let's do all Verify 3.x as L4 package and further releases as L5 package including backport to 3.x on improvements done on further releases (by PR on branches)

**Comment by Toddish** [comment]
@Maxime-BHA It was more the install count on Packagist I was annoyed at losing! I'd have to delete Verify on there iirc, and add it as a new package. As ideally, I'd rename this to just Toddish/Verify, and the new tagged version 4 would be Laravel 5 compatible.

I'd then rename Toddish/Verify to Toddish/Verify-L3, and set it out to pasture (no idea if people even use it anymore).

**Comment by Toddish** [comment]
I've started work on this, and the package is pretty much done.

Just the docs, tests and package/repo name left to sort.

If anyone wants to give it a try out, use:

    "toddish/verify": "dev-feature/L5

In your composer.json.

**Comment by christian-thomas** [comment]
Nice one Todd, I'll get it pulled down on a couple of L5 projects this week and have a play. New commands looks useful though.

Cheers!

**Comment by Toddish** [comment]
That'd be great cheers.

Bear in mind I've taken out the log in exceptions!

I've come up with a new way to handle them (I think), so currently you can log in if you're unverified or disabled.

**Comment by Maxime-BHA** [comment]
@Toddish you should stop using Facade for basic things like `Str` or `Config`, you can now call them like this `config()`

**Comment by Toddish** [comment]
I was unsure about using the helper methods, as using a class (albeit a facade) seemed nicer.

I've switched out all facades now anyway, and replaced them with the helpers.

I think this is ready to be tagged now, I just need to update me site with new docs.

I've added a new Auth::verify method, too.

**Comment by Maxime-BHA** [comment]
@Toddish now Laravel 5 has `Illuminate\Contracts\Auth\CanResetPassword` which is the interface/contract that make possible a reset of the password and there is also the trait `Illuminate\Auth\Passwords\CanResetPassword`, couldn't we create a similar trait/contract and extends the PasswordBroker from default Auth to break the passwork and send the new one through `Illuminate\Auth\Passwords\PasswordBroker`.

See API :
http://laravel.com/api/5.0/Illuminate/Contracts/Auth/CanResetPassword.html
http://laravel.com/api/5.0/Illuminate/Auth/Passwords/CanResetPassword.html

http://laravel.com/api/5.0/Illuminate/Contracts/Auth/PasswordBroker.html
http://laravel.com/api/5.0/Illuminate/Auth/Passwords/PasswordBroker.html

https://github.com/illuminate/auth/tree/master/Passwords
https://github.com/illuminate/contracts/tree/master/Auth

**Comment by smartfaceweb** [comment]
@Toddish any updates on when you'll release L5 stable?

**Comment by Toddish** [comment]
Sorry this has taken so long, it's always the last push!

I'm halfway through the documentation, and was trying to avoid tagging before that was done.

I'll try and get it all sorted tomorrow, but it might be next week.

I don't think there'll be any changes to the actual code, so the branch should be safe to use.

I'll update when it's all sorted :)

**Comment by Toddish** [comment]
Forgot to say, this is all done now :)
